FROM php:8.1-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    curl

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Other configurations...

# Install the MongoDB extension
RUN apt-get update && apt-get install -y libssl-dev wget git unzip libzip-dev \
    && pecl install mongodb \
    && docker-php-ext-enable mongodb

